### ISSUE TITLE
WPForms ... ?

### ISSUE THREAD

**Issue by leepeterson** [loumray/wpforms#1]
Is this plugin a fork, a rework, or a new form management plugin for WordPress? Curious about the name given there's already a [WPForms](https://wpforms.com).

**Comment by loumray** [comment]
As you can see, first commit is from 3 years ago, so it is nothing new. This is no fork or rework and as nothing to do with WPForms.  It is 100% "authentic code".

I have been using this repos mainly to create form fields to be used mostly in WP admin metaboxes. But the purpose is to provide developers a library of fields that can be used both on the theme side and admin side of wordpress.

You are welcome to use it, fork it, contribute to it, if it may be of some use to you.

**Comment by leepeterson** [comment]
Awesome! Just checking. Never know if someone's forked and infected a legit plugin, redistributed as malware or similar. And, yes, I saw 3+ years ago which is newer than the commercialized WPForms. 

Will check it out. Looking for a basis for an internal tool here at the office. Thanks!
