### ISSUE TITLE
Bug when content dir is not wp-content

### ISSUE THREAD

**Issue by plaurent75** [loumray/wpforms#2]
Hi, the's an error in your method getBaseUrl()

As wordpress allow to change the name of the content dir, you should not use wp-content in this function, this directory is defined by WP_CONTENT_DIR :

$pos = strpos($dirFromFile, 'wp-content')+strlen('wp-content');

Should be :

$pos = strpos($dirFromFile, WP_CONTENT_DIR)+strlen(WP_CONTENT_DIR);

**Comment by loumray** [comment]
Hi!

Nice pickup, just fixed this in this commit e90ec214fb0da30f794127df0b195dfb4f707dff, thank you!
